services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Paris # initdb uses TZ as the value it writes to postgres.conf
      - PGTZ=Europe/Paris # libpq checks for PGTZ to determine which time zone to set (for the client) after connecting (to the server)
    volumes:
      # Bind the docker volume 'db-data' to the container
      - db-data:/var/lib/postgresql/data:rw
    ports:
      # Binds user-defined port to default postgres's 5432
      - "5432:5432"

volumes:
  # Creates a db-data docker volume.
  # Clear the volume with `docker volume prune`
  db-data:
